# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - kb1rd_more_dispersion
      # https://github.com/orgs/community/discussions/24657#discussioncomment-3244894
      # So, we have to resort to messy hacks to force github to just build
      # Force push to this branch to trigger a build without messing up the PR branch
      - gh_actions_trigger_hack
  #workflow_dispatch:
  #  inputs:
  #    environment: # I think environment is what I want here, but I can't make sense of GH docs...
  #      description: 'Environment to build'
  #      type: environment
  #      required: true

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/
